export const GAME_RESTART = 'GAME_RESTART'
export const PLAYER_ONE_SELECTED_SHAPE = 'PLAYER_ONE_SELECTED_SHAPE'
export const PLAYER_TWO_SELECTED_SHAPE = 'PLAYER_TWO_SELECTED_SHAPE'
export const UPDATE_SCORE = 'UPDATE_SCORE'
